DIRECTORY:
  data: ./data/01_split
  sample: ./data/sample_submission.csv
  phase: test 

EXPERIMENT:
  serial: xgb_20220613_195724

LABEL_ENCODING:
  other: 0
  noise: 1
  normal: 2
  in: 3
  out: 4
  